### ISSUE TITLE
Benchmark UI libraries

### ISSUE THREAD

**Issue by benjaminBoboul** [benjaminBoboul/cardio#2]
# Tasks

- [ ] https://github.com/ArthurSonzogni/FTXUI
- [ ] https://github.com/dankamongmen/notcurses
- [ ] https://github.com/gansm/finalcut
- [ ] https://github.com/ggerganov/imtui
